namespace GenosStore.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RequiredFix : DbMigration
    {
        public override void Up()
        {
            RenameColumn(table: "public.Items", name: "ActiveDiscountId", newName: "ActiveDiscount_Id");
            RenameColumn(table: "public.Items", name: "ItemTypeId", newName: "ItemType_Id");
            RenameColumn(table: "public.Items", name: "VendorId", newName: "Vendor_Id");
            RenameColumn(table: "public.Orders", name: "CustomerId", newName: "Customer_Id");
            RenameColumn(table: "public.CPUs", name: "CPUCoreId", newName: "CPUCore_Id");
            RenameColumn(table: "public.CPUCores", name: "VendorId", newName: "Vendor_Id");
            RenameColumn(table: "public.GraphicsCards", name: "GPUId", newName: "GPU_Id");
            RenameColumn(table: "public.GPUs", name: "VendorId", newName: "Vendor_Id");
            RenameColumn(table: "public.PreparedAssemblies", name: "ComputerCaseId", newName: "ComputerCase_Id");
            RenameColumn(table: "public.PreparedAssemblies", name: "CPUId", newName: "CPU_Id");
            RenameColumn(table: "public.PreparedAssemblies", name: "CPUCoolerId", newName: "CPUCooler_Id");
            RenameColumn(table: "public.PreparedAssemblies", name: "DisplayId", newName: "Display_Id");
            RenameColumn(table: "public.PreparedAssemblies", name: "GraphicsCardId", newName: "GraphicsCard_Id");
            RenameColumn(table: "public.PreparedAssemblies", name: "KeyboardId", newName: "Keyboard_Id");
            RenameColumn(table: "public.PreparedAssemblies", name: "MotherboardId", newName: "Motherboard_Id");
            RenameColumn(table: "public.PreparedAssemblies", name: "MouseId", newName: "Mouse_Id");
            RenameColumn(table: "public.PreparedAssemblies", name: "PowerSupplyId", newName: "PowerSupply_Id");
            RenameColumn(table: "public.Displays", name: "DefinitionId", newName: "Definition_Id");
            RenameIndex(table: "public.Orders", name: "IX_CustomerId", newName: "IX_Customer_Id");
            RenameIndex(table: "public.Items", name: "IX_ActiveDiscountId", newName: "IX_ActiveDiscount_Id");
            RenameIndex(table: "public.Items", name: "IX_ItemTypeId", newName: "IX_ItemType_Id");
            RenameIndex(table: "public.Items", name: "IX_VendorId", newName: "IX_Vendor_Id");
            RenameIndex(table: "public.CPUCores", name: "IX_VendorId", newName: "IX_Vendor_Id");
            RenameIndex(table: "public.GPUs", name: "IX_VendorId", newName: "IX_Vendor_Id");
            RenameIndex(table: "public.CPUs", name: "IX_CPUCoreId", newName: "IX_CPUCore_Id");
            RenameIndex(table: "public.Displays", name: "IX_DefinitionId", newName: "IX_Definition_Id");
            RenameIndex(table: "public.GraphicsCards", name: "IX_GPUId", newName: "IX_GPU_Id");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_ComputerCaseId", newName: "IX_ComputerCase_Id");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_CPUId", newName: "IX_CPU_Id");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_CPUCoolerId", newName: "IX_CPUCooler_Id");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_DisplayId", newName: "IX_Display_Id");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_GraphicsCardId", newName: "IX_GraphicsCard_Id");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_KeyboardId", newName: "IX_Keyboard_Id");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_MotherboardId", newName: "IX_Motherboard_Id");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_MouseId", newName: "IX_Mouse_Id");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_PowerSupplyId", newName: "IX_PowerSupply_Id");
            AddColumn("public.Items", "ImageBase64", c => c.String());
            AlterColumn("public.IndividualEntities", "Name", c => c.String(nullable: false));
            AlterColumn("public.IndividualEntities", "Surname", c => c.String(nullable: false));
            AlterColumn("public.IndividualEntities", "PhoneNumber", c => c.String(nullable: false));
            AlterColumn("public.LegalEntities", "PhysicalAddress", c => c.String(nullable: false));
            AlterColumn("public.LegalEntities", "LegalAddress", c => c.String(nullable: false));
            AlterColumn("public.Users", "Email", c => c.String(nullable: false));
            AlterColumn("public.Users", "PasswordHash", c => c.String(nullable: false));
            AlterColumn("public.Users", "Salt", c => c.String(nullable: false));
            AlterColumn("public.SimpleComputerComponents", "Model", c => c.String(nullable: false));
            AlterColumn("public.SimpleComputerComponents", "Name", c => c.String(nullable: false));
            AlterColumn("public.SimpleComputerComponentTypes", "Name", c => c.String(nullable: false));
            AlterColumn("public.BankCards", "Owner", c => c.String(nullable: false));
            AlterColumn("public.BankSystems", "Name", c => c.String(nullable: false));
            AlterColumn("public.Certificates80Plus", "Name", c => c.String(nullable: false));
            AlterColumn("public.CoolerMaterials", "Name", c => c.String(nullable: false));
            AlterColumn("public.Items", "Description", c => c.String(nullable: false));
            AlterColumn("public.Items", "Model", c => c.String(nullable: false));
            AlterColumn("public.Items", "Name", c => c.String(nullable: false));
            AlterColumn("public.ItemTypes", "Name", c => c.String(nullable: false));
            AlterColumn("public.Vendors", "Name", c => c.String(nullable: false));
            AlterColumn("public.CPUCores", "Name", c => c.String(nullable: false));
            AlterColumn("public.DCPUSocket", "Name", c => c.String(nullable: false));
            AlterColumn("public.MotherboardFormFactors", "Name", c => c.String(nullable: false));
            AlterColumn("public.PCIEVersions", "Name", c => c.String(nullable: false));
            AlterColumn("public.RAMTypes", "Name", c => c.String(nullable: false));
            AlterColumn("public.VideoPorts", "Name", c => c.String(nullable: false));
            AlterColumn("public.GPUs", "Model", c => c.String(nullable: false));
            AlterColumn("public.GPUs", "Name", c => c.String(nullable: false));
            AlterColumn("public.MatrixTypes", "Name", c => c.String(nullable: false));
            AlterColumn("public.Underlights", "Name", c => c.String(nullable: false));
            AlterColumn("public.VesaSizes", "Name", c => c.String(nullable: false));
            AlterColumn("public.KeyboardType", "Name", c => c.String(nullable: false));
            AlterColumn("public.KeyboardTypesizes", "Name", c => c.String(nullable: false));
            AlterColumn("public.OrderStatus", "Name", c => c.String(nullable: false));
            AlterColumn("public.ComputerCaseTypesizes", "Name", c => c.String(nullable: false));
            DropColumn("public.SimpleComputerComponents", "SimpleComputerComponentTypeId");
            DropColumn("public.ComputerCases", "ComputerCaseTypesizeId");
            DropColumn("public.Items", "PathToImage");
            DropColumn("public.CPUs", "CPUSockerId");
            DropColumn("public.Motherboards", "MotherboardFormFactorId");
            DropColumn("public.Motherboards", "CPUSocketId");
            DropColumn("public.Motherboards", "MotherboardChipsetId");
            DropColumn("public.Motherboards", "AudioChipsetId");
            DropColumn("public.Motherboards", "NetworkAdapterId");
            DropColumn("public.CPUCoolers", "FoundationMaterialId");
            DropColumn("public.CPUCoolers", "RadiatroMaterialId");
            DropColumn("public.Displays", "MatrixTypeId");
            DropColumn("public.Displays", "UnderlightId");
            DropColumn("public.Displays", "VesaSizeId");
            DropColumn("public.Keyboards", "KeyboardTypesizeId");
            DropColumn("public.Keyboards", "KeyboardTypeId");
            DropColumn("public.PowerSupplies", "Certiticate80PlusId");
            DropColumn("public.RAMs", "RamTypeId");
            DropColumn("public.SSDs", "SSDControllerId");
            DropColumn("public.Orders", "OrderStatusId");
        }
        
        public override void Down()
        {
            AddColumn("public.Orders", "OrderStatusId", c => c.Int(nullable: false));
            AddColumn("public.SSDs", "SSDControllerId", c => c.Int(nullable: false));
            AddColumn("public.RAMs", "RamTypeId", c => c.Int(nullable: false));
            AddColumn("public.PowerSupplies", "Certiticate80PlusId", c => c.Int(nullable: false));
            AddColumn("public.Keyboards", "KeyboardTypeId", c => c.Int(nullable: false));
            AddColumn("public.Keyboards", "KeyboardTypesizeId", c => c.Int(nullable: false));
            AddColumn("public.Displays", "VesaSizeId", c => c.Int(nullable: false));
            AddColumn("public.Displays", "UnderlightId", c => c.Int(nullable: false));
            AddColumn("public.Displays", "MatrixTypeId", c => c.Int(nullable: false));
            AddColumn("public.CPUCoolers", "RadiatroMaterialId", c => c.Int(nullable: false));
            AddColumn("public.CPUCoolers", "FoundationMaterialId", c => c.Int(nullable: false));
            AddColumn("public.Motherboards", "NetworkAdapterId", c => c.Int(nullable: false));
            AddColumn("public.Motherboards", "AudioChipsetId", c => c.Int(nullable: false));
            AddColumn("public.Motherboards", "MotherboardChipsetId", c => c.Int(nullable: false));
            AddColumn("public.Motherboards", "CPUSocketId", c => c.Int(nullable: false));
            AddColumn("public.Motherboards", "MotherboardFormFactorId", c => c.Int(nullable: false));
            AddColumn("public.CPUs", "CPUSockerId", c => c.Int(nullable: false));
            AddColumn("public.Items", "PathToImage", c => c.String());
            AddColumn("public.ComputerCases", "ComputerCaseTypesizeId", c => c.Int(nullable: false));
            AddColumn("public.SimpleComputerComponents", "SimpleComputerComponentTypeId", c => c.Int(nullable: false));
            AlterColumn("public.ComputerCaseTypesizes", "Name", c => c.String());
            AlterColumn("public.OrderStatus", "Name", c => c.String());
            AlterColumn("public.KeyboardTypesizes", "Name", c => c.String());
            AlterColumn("public.KeyboardType", "Name", c => c.String());
            AlterColumn("public.VesaSizes", "Name", c => c.String());
            AlterColumn("public.Underlights", "Name", c => c.String());
            AlterColumn("public.MatrixTypes", "Name", c => c.String());
            AlterColumn("public.GPUs", "Name", c => c.String());
            AlterColumn("public.GPUs", "Model", c => c.String());
            AlterColumn("public.VideoPorts", "Name", c => c.String());
            AlterColumn("public.RAMTypes", "Name", c => c.String());
            AlterColumn("public.PCIEVersions", "Name", c => c.String());
            AlterColumn("public.MotherboardFormFactors", "Name", c => c.String());
            AlterColumn("public.DCPUSocket", "Name", c => c.String());
            AlterColumn("public.CPUCores", "Name", c => c.String());
            AlterColumn("public.Vendors", "Name", c => c.String());
            AlterColumn("public.ItemTypes", "Name", c => c.String());
            AlterColumn("public.Items", "Name", c => c.String());
            AlterColumn("public.Items", "Model", c => c.String());
            AlterColumn("public.Items", "Description", c => c.String());
            AlterColumn("public.CoolerMaterials", "Name", c => c.String());
            AlterColumn("public.Certificates80Plus", "Name", c => c.String());
            AlterColumn("public.BankSystems", "Name", c => c.String());
            AlterColumn("public.BankCards", "Owner", c => c.String());
            AlterColumn("public.SimpleComputerComponentTypes", "Name", c => c.String());
            AlterColumn("public.SimpleComputerComponents", "Name", c => c.String());
            AlterColumn("public.SimpleComputerComponents", "Model", c => c.String());
            AlterColumn("public.Users", "Salt", c => c.String());
            AlterColumn("public.Users", "PasswordHash", c => c.String());
            AlterColumn("public.Users", "Email", c => c.String());
            AlterColumn("public.LegalEntities", "LegalAddress", c => c.String());
            AlterColumn("public.LegalEntities", "PhysicalAddress", c => c.String());
            AlterColumn("public.IndividualEntities", "PhoneNumber", c => c.String());
            AlterColumn("public.IndividualEntities", "Surname", c => c.String());
            AlterColumn("public.IndividualEntities", "Name", c => c.String());
            DropColumn("public.Items", "ImageBase64");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_PowerSupply_Id", newName: "IX_PowerSupplyId");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_Mouse_Id", newName: "IX_MouseId");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_Motherboard_Id", newName: "IX_MotherboardId");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_Keyboard_Id", newName: "IX_KeyboardId");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_GraphicsCard_Id", newName: "IX_GraphicsCardId");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_Display_Id", newName: "IX_DisplayId");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_CPUCooler_Id", newName: "IX_CPUCoolerId");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_CPU_Id", newName: "IX_CPUId");
            RenameIndex(table: "public.PreparedAssemblies", name: "IX_ComputerCase_Id", newName: "IX_ComputerCaseId");
            RenameIndex(table: "public.GraphicsCards", name: "IX_GPU_Id", newName: "IX_GPUId");
            RenameIndex(table: "public.Displays", name: "IX_Definition_Id", newName: "IX_DefinitionId");
            RenameIndex(table: "public.CPUs", name: "IX_CPUCore_Id", newName: "IX_CPUCoreId");
            RenameIndex(table: "public.GPUs", name: "IX_Vendor_Id", newName: "IX_VendorId");
            RenameIndex(table: "public.CPUCores", name: "IX_Vendor_Id", newName: "IX_VendorId");
            RenameIndex(table: "public.Items", name: "IX_Vendor_Id", newName: "IX_VendorId");
            RenameIndex(table: "public.Items", name: "IX_ItemType_Id", newName: "IX_ItemTypeId");
            RenameIndex(table: "public.Items", name: "IX_ActiveDiscount_Id", newName: "IX_ActiveDiscountId");
            RenameIndex(table: "public.Orders", name: "IX_Customer_Id", newName: "IX_CustomerId");
            RenameColumn(table: "public.Displays", name: "Definition_Id", newName: "DefinitionId");
            RenameColumn(table: "public.PreparedAssemblies", name: "PowerSupply_Id", newName: "PowerSupplyId");
            RenameColumn(table: "public.PreparedAssemblies", name: "Mouse_Id", newName: "MouseId");
            RenameColumn(table: "public.PreparedAssemblies", name: "Motherboard_Id", newName: "MotherboardId");
            RenameColumn(table: "public.PreparedAssemblies", name: "Keyboard_Id", newName: "KeyboardId");
            RenameColumn(table: "public.PreparedAssemblies", name: "GraphicsCard_Id", newName: "GraphicsCardId");
            RenameColumn(table: "public.PreparedAssemblies", name: "Display_Id", newName: "DisplayId");
            RenameColumn(table: "public.PreparedAssemblies", name: "CPUCooler_Id", newName: "CPUCoolerId");
            RenameColumn(table: "public.PreparedAssemblies", name: "CPU_Id", newName: "CPUId");
            RenameColumn(table: "public.PreparedAssemblies", name: "ComputerCase_Id", newName: "ComputerCaseId");
            RenameColumn(table: "public.GPUs", name: "Vendor_Id", newName: "VendorId");
            RenameColumn(table: "public.GraphicsCards", name: "GPU_Id", newName: "GPUId");
            RenameColumn(table: "public.CPUCores", name: "Vendor_Id", newName: "VendorId");
            RenameColumn(table: "public.CPUs", name: "CPUCore_Id", newName: "CPUCoreId");
            RenameColumn(table: "public.Orders", name: "Customer_Id", newName: "CustomerId");
            RenameColumn(table: "public.Items", name: "Vendor_Id", newName: "VendorId");
            RenameColumn(table: "public.Items", name: "ItemType_Id", newName: "ItemTypeId");
            RenameColumn(table: "public.Items", name: "ActiveDiscount_Id", newName: "ActiveDiscountId");
        }
    }
}
